version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432
